server:
  port: 8085

spring:
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST}
    port: 5672
    username: ${SPRING_RABBITMQ_USERNAME}
    password: ${SPRING_RABBITMQ_PASSWORD}


eureka:
  client:
    serviceUrl:
      defaultZone: "${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}"
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 5
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5
